### ISSUE TITLE
Repository structure for 0.4 is not compliant

### ISSUE THREAD

**Issue by noshitsherlock** [Danielhiversen/home_assistant_tibber_custom#31]
Repository structure for 0.4 is not compliant is the message I get when trying to add it.

**Comment by wmountain1** [comment]
Did you try choosing integration in the drop-down menu?

**Comment by noshitsherlock** [comment]
@wmountain1 That worked! Was able to install it 👍🏻 But how do I use it afterward? Rebooted host and I can see it installed integration in HACS.

**Comment by wmountain1** [comment]
If you have added tibber_custom: to your configuration.yaml, you just have to add a new card to the dashboard and select "by entity". Then search for camera and it should show up. Select, continue, add to dashboard. If the pic isn't showing, edit the card after adding it and change camera view to live.

I don't know whether all of these steps are necessary as I am totally new to home assistant, but that's how I got it to work.

Also, at first I thought there was something wrong because the current price shown was different from what I was seeing in the Tibber app, but that was because I hadn't chosen to see the total price in the app (with taxes, etc).

**Comment by noshitsherlock** [comment]
@wmountain1 Thanks a lot for this 🙌🏻 What explicitly did you add to configuration.yml? Thanks again.

**Comment by wmountain1** [comment]
I just added "tibber_custom:" under "default_config:", then saved it.

**Comment by noshitsherlock** [comment]
> I just added "tibber_custom:" under "default_config:", then saved it.

Cool I will try that later and see if it works! Thanks a lot for the help 😎
